let genButton;

function setup() {
  noCanvas();
  background(255);
  textAlign(LEFT, TOP);
  textSize(24);
  genButton = createButton("Click to generate");
  genButton.mousePressed(generate);
}

function draw() {
}

function generate() {
  var grammar = tracery.createGrammar(grammarSource);
  grammar.addModifiers(tracery.baseEngModifiers);
  var output = grammar.flatten("#origin#");
  if (document.querySelector("#output")) {
    document.querySelector("#output").remove();
  }
  createP(output).id("output");
}

var grammarSource = {
  "origin": [
    "#sentence1##sentence2##sentence3##sentence4##sentence5##sentence6##sentence7##sentence8##sentence9##sentence10##sentence11##sentence12##sentence13##sentence14##sentence15##sentence16##sentence17##sentence18##sentence19##sentence20##sentence21##sentence22##sentence23##sentence24##sentence25##sentence26##sentence27##sentence28##sentence29##sentence30##sentence31#"
  ],
  "sentence1": ["The Wolf consumed the potato and not much later there were grand fortresses, buzzing metropolises, and vessels traversing the sea. The golden dragon observed the spud soar past the tree and he was snoring so profoundly that the boughs quivered. ",
    "The Wolf devoured the potato and it was not much later that massive castles, thriving cities, and vessels sailing the sea were visible. The golden dragon observed the potato pass the tree and he was snoozing so fiercely that the twigs shuddered. ",
    "The Wolf ate at the potato, and it was not long before: towering castles, bustling cities, and ships sailing on the ocean. The golden dragon watched the potato fly by the tree and he was snoring so loud that the branches shook. ",
    "The Wolf gobbled the potato and shortly afterwards there were colossal castles, bustling towns, and boats sailing the ocean. The golden dragon noticed the potato zip past the tree and he was dozing so deeply that the branches trembled. ",
    "The Wolf ingested the potato and soon thereafter there were citadels towering, villages bustling, and boats sailing the ocean. The golden dragon observed the potato drift by the tree and he was snoozing so hard that the branches trembled. "],
  "sentence2": ["The Wolf had held its ebony paws up against the window, and the children viewed them from criminals. They shouted and praised the dragon, and the tiniest Kid sprinted after it. ", 
    "But the Wolf had laid his black paws against the window, and the children saw them from bandits. They cheered and applauded the dragon, and the youngest Kid ran with her. ", 
    "The Wolf had placed its black paws up against the window, and the children noticed them from crooks. They shouted and celebrated the dragon, and the littlest Kid ran in its direction. ", 
    "The Wolf had propped its charcoal paws against the window, and the children spotted them from miscreants. They shouted and admired the dragon, and the youngest Kid raced after it. ", 
    "The Wolf had rested its dark paws against the window, and the children observed them from thieves. They cheered and applauded the dragon, and the smallest Kid ran with it. "],
  "sentence3": ["The Golden Dragon hastened to a baker and posed, “I have a longing to observe the world from the air, yet I am not able to fly. Do you think it would be possible for you to carry me on a journey?” ", 
    "The Golden Dragon hastened to a baker and inquired, “I have a deep wish to observe the world from the sky, yet I cannot take to the air. Could you possibly convey me on a ride?” ", 
    "Then the Golden Dragon ran to a baker, and said, “I have always wanted to see the world from the sky, but I can't fly. Do you think you could take me for a ride?” ", 
    "The Golden Dragon hastened to a baker and inquired, “I have a strong desire to view the world from the sky, yet I am not able to fly. Might you be able to transport me on a ride?” ", 
    "The Golden Dragon hastened to a baker and inquired, “I have a strong yearning to view the world from the sky, yet I cannot fly. Do you think you could take me on a journey?” "],
  "sentence4": ["And when the baker had rubbed his feet over, he ran to the miller and said, 'Hop on.' The potato climbed onto the dragon's back, and they took off into the sky. But the frog said, “If you will not do it, I will devour you.” Then the frog smiled. 'That's the spirit. I believe in you, little potato. And to help you on your journey, I will give you a special power. I will turn you into a magical potato, one that can sprout wings and fly.' ", 
    "When the baker had finished rubbing his feet, he hastened to the miller and shouted, 'Climb on!' The potato clambered onto the dragon's back, and they flew away into the sky. However, the frog declared, 'If you won't, I will swallow you.' Then the frog grinned. 'That's the courage. I have faith in you, little potato. And to aid you on your journey, I will give you a special capability. I will turn you into a supernatural potato, one that can sprout wings and fly.' ", 
    "After the baker completed massaging his toes, he hurried to the miller and exclaimed, 'Jump on!' The potato scrambled up the dragon's back, and they began to soar through the clouds. But the frog stated, 'If you won't, I shall consume you.' Then the frog smiled. 'That's the attitude. I am confident in you, little potato. To assist you on your mission, I shall bestow upon you a unique power. I will transform you into an enchanted potato, able to sprout wings and soar.'' ", ],
  "sentence5": ["At that moment, the unfortunate person proceeded for a short period and then uttered, 'Allow me in, Kids! Your lovely small mom has arrived home, and has brought something for each of you from the woods.”  ", 
    "Now, the wretch went for for a moment and then said, “Open the door for me, Children! Your dear little mother has come home, and has brought every one of you something from the forest with her.' ", 
    "At that time, the wretched man moved for a bit and afterwards exclaimed, “Unlock the door for me, Children! Your dear tiny mother has returned, and has brought each of you something from the forest with her.” " ],
  "sentence6": ["The little Kids cried, 'First showing everyone that even the most unexpected pairs could achieve greatness.' ", 
    "The children sobbed, 'Demonstrating to all that even the most unlikely duos can reach extraordinary heights.' ", 
    "The small children wept, 'Proving to everyone that even the most unexpected alliances could reach greatness.' " ],
  "sentence7": ["Then he put his paws in through the window. And when the Kids saw that they were amazed. They had never seen a dragon before. But who should come in but the Wolf! ", 
    "He stretched his claws in through the window, to the surprise of the children. None of them had ever witnessed a dragon before, yet in came the Wolf! ", 
    "Alternatively, He pushed his paws into the window, causing the kids to be astounded. They had never seen a dragon before and yet here was the Wolf! " ],
  "sentence8": ["They were terrified and wanted to hide themselves. One day, while taking a stroll through the village, it heard a loud roar coming from the nearby forest. Curious, the potato rolled towards the source of the noise. But the Wolf found them all and made no delay, but swallowed one after the other down his throat. The youngest in the clock-case was the only with their trusty farming tools. ", 
    "One day, whilst ambling around the village, a loud roar reverberated from the neighbouring woodland. Intrigued, the potato trundled in the direction of the noise. However, the Wolf discovered them all and did not hesitate, swiftly swallowing each one up his gullet. The youngest in the time-piece was the only one with their dependable farming implements. ", 
    "One day, as they strolled through the village, a loud bellow echoed from the close-by forest. Inquisitive, the potato wheeled towards the origin of the sound. Yet the Wolf spotted them all and acted without delay, promptly devouring one after the other down his gullet. The youngest in the clock-case was the only one with their reliable agricultural tools. " ],
  "sentence9": ["When the Wolf had satisfied his appetite, he took himself off, laid himself down the dirt path, it encountered a rabbit who was lounging in the grass. ", 
    "When the Wolf had filled his stomach, he left, reclined on the dirt trail, and came across a rabbit idling in the grass. ", 
    "Having eaten his fill, the Wolf left, lying down on the dirt path and stumbled upon a rabbit lounging in the grass. " ],
  "sentence10": ["Soon afterward, the old Goat came home again from the forest. Ah! what a sight she saw there! The house-door stood out above the rest in Tater Town was also there. It had always dreamt of becoming something more than a little Kid thrust its head out, and when she had cut farther, all the beautiful sights it had never seen before. ", 
    "Shortly thereafter, the aged Goat returned from the woodland. Oh! What an incredible spectacle she beheld there! The abode-door which stood prominent among the other dwellings in Tater Town was present as well. It had hoped to attain something more than it was, and when she had cut further, it beheld all the marvellous views it had never laid eyes on before. ", 
    "In the blink of an eye, the aged Goat was back from the forest. Wow! What a breathtaking sight she espied there! The entrance to the house which stood out among the others in Tater Town was also there. It had long desired to become something more than it was and when she went on, she saw all the stunning sights it had never witnessed before. " ],
  "sentence11": ["She sought her children, but they were a sight to behold, with their scaly bodies, sharp talons, and powerful wings. But there was one dragon that was different from the rest. This and made his voice soft with it. ", 
    "She searched for her offspring, yet the sight of them was remarkable, with their scaly skin, pointed claws, and formidable wings. Yet, one dragon was distinct from the others, and he spoke softly. ", 
    "She looked for her kids, and they were a sight to observe, with their reptilian bodies, razor-like talons, and mighty wings. But one dragon was unlike the rest and he spoke in a gentle tone. " ],
  "sentence12": ["At length, in her grief she went on many adventures together, using their unique abilities to help others and explore the world. They became known throughout the land as many of them into his stomach as they could get in. And the mother sewed him up to the beast and said, 'Let me help you with that branch.' ", 
    "After much sorrow, she embarked on a number of quests with her distinct capabilities, seeking to serve others and traverse the planet. They gained acclaim everywhere for their deeds, stuffing as much of it into his belly as feasible. Subsequently, the woman stitched him to the animal and said, 'Allow me to assist you with that branch.' ", 
    "Eventually, in her distress she set out on a multitude of journeys together, utilizing their special capabilities to assist others and investigate the world. They became renowned throughout the land as they crammed as much of it into his abdomen as they could. Subsequently, the mother sewed him to the creature and stated, 'Let me help you with that branch.' " ],
  "sentence13": ["The dragon was surprised but grateful for the offer. It opened its mouth and the potato used its sturdy body head out, and when she had cut farther, all six sprang out one after another, and were all still alive, and had suffered no hurt whatever, for greatness and that it would make a difference in the world. ", 
    "The dragon was taken aback yet thankful for the proposal. It parted its lips and the spud utilized its robust outer shell to exit, and when she had cut deeper, all six emerged in succession, and were still alive, and had experienced no injury whatsoever, for greatness and that it would have an effect on the world. ", 
    "The dragon was astonished but appreciative for the proposition. It unhinged its jaw and the tuber employed its robust external covering to vacate, and when she had excised further, all six shot out one after the other, and were all still alive, and had endured no harm whatsoever, for greatness and that it would create an impact on the world. " ],
  "sentence14": ["And so that he was not aware of anything and never once stirred. ", 
    "So that he remained oblivious and never moved an inch. ", 
    "He was completely ignorant and never moved a muscle. " ],
  "sentence15": ["When the Wolf had had his sleep out, he got closer, the potato saw a magnificent dragon with shimmering scales and piercing red eyes. The dragon had swallowed them whole. What rejoicing there was! They became known throughout the kingdom as symbols of courage, determination, and hope. And the kingdom thrived, thanks to their bravery and spirit.", 
    "When the Wolf had had his rest, he approached, the potato viewed a splendid dragon with glistening scales and sharp red eyes. The dragon had engulfed them completely. What celebration there was! They became renowned all over the realm as representations of bravery, resolution, and expectation. And the realm flourished, owing to their valor and vigor. ", 
    "When the Wolf had his slumber, he advanced, the potato beheld a magnificent dragon with gleaming scales and piercing red eyes. The dragon had gulped them whole. What rejoicing there was! They became renowned across the kingdom as icons of courage, resolution, and optimism. And the kingdom prospered, due to their boldness and verve. " ],
  "sentence16": ["The frog looked at the potato thoughtfully. 'I be still alive?' ", 
    "The frog stared contemplatively at the potato. 'Am I still alive?' ", 
    "The frog gazed ponderously at the potato. 'Could I still be alive?' " ],
  "sentence17": ["Then the Kid had to run home and fetch scissors, and a needle and thread, and the Goat cut open the monster’s stomach. Hardly had she sure that they were protected and cared for. The dragons lived in a vast forest at the edge of the kingdom, and it was there that they spent their days. ", 
    "Then the Kid had to sprint back to his house and grab scissors, and a needle and thread, and the Goat sliced open the monster’s abdomen. Scarcely had she made sure that they were shielded and looked after. The dragons resided in a huge woodland at the boundary of the kingdom, and that was where they occupied their time. ", 
    "The Kid had to dash home and acquire scissors, and a needle and thread, and the Goat ripped open the monster’s belly. Just after she confirmed that they were defended and taken care of. The dragons lived in a great forest at the fringe of the kingdom, and it was there that they passed their days. " ],
  "sentence18": ["The potato thought for a moment and then said, 'I know it won't be easy, but I won't give up. I will not open the door, our mother has not black feet like you. You are the Wolf!' ", 
    "The potato hesitated briefly and then declared, 'I understand that it won't be a simple task, yet I will not surrender. I will not unlock the door, our mother doesn't possess the same dark feet as yours. You are the Wolf!' ", 
    "The potato paused momentarily and then declared, 'I comprehend that it won't be a straightforward endeavor, yet I won't quit. I will not unlock the door, our mother doesn't have the same black feet as you. You are the Wolf!' " ],
  "sentence19": ["In the depths of the vast forest, the golden dragon had grown old and weary. It had lived a long and happy life, but it knew that its time was coming to an end. It had watched as generations of dragons had come and gone, and it had seen the world change and grow. But despite all the changes, the golden dragon knew that it would always be a part of the kingdom's heritage. ", 
    "Deep in the boundless woodlands, the golden dragon was aging and weary. It had experienced a long and joyful life, but it realized its life was almost over. It had seen the emergence and disappearance of many dragons, and it had noticed the world alter and develop. Nevertheless, the golden dragon realized it would forever be a piece of the kingdom's legacy. ", 
    "Far down in the immense forest, the golden dragon had aged and become tired. It had led an extended and contented life, but it knew its days were numbered. It had observed as many dragons came and went, and it had watched the world evolve and expand. In spite of all the alterations, the golden dragon recognized it would always be a part of the kingdom's heritage. " ],
  "sentence20": ["As the golden dragon flew over the forest, it felt a sudden pain in its chest. It knew that it was time to say goodbye to the world. It closed its eyes and let out a deep breath. But as it did, it heard a loud roar coming from the distance. The golden dragon opened its eyes and saw a magnificent dragon with shimmering scales and piercing red eyes. The dragon had a huge tree branch stuck in its mouth, and it was thrashing around in agony. ", 
    "As the golden dragon soared above the woods, a sharp pang in its chest abruptly appeared. It understood that it was time to bid farewell to the universe. It shut its eyes and inhaled profoundly. But as it did, a loud roar was heard from the horizon. The golden dragon opened its eyes and perceived a stunning dragon with gleaming scales and dazzling red eyes. The dragon had a huge tree branch lodged in its mouth, and it was struggling in misery. ", 
    "As the golden dragon flew over the forest, a sudden pain in its chest became evident. It knew it was time to say goodbye to the world. It closed its eyes and let out a deep breath. But as it did, it heard a loud roar coming from the distance. The golden dragon opened its eyes and saw a magnificent dragon with shimmering scales and piercing red eyes. The dragon had a huge tree branch stuck in its mouth, and it was thrashing around in agony. " ],
  "sentence21": ["The golden dragon knew that it had to help. It flew down to the dragon and gently pulled the branch from its mouth. The other dragon was grateful and thanked the golden dragon for its help. They talked for a while, and the golden dragon learned that the other dragon was a king from a distant land. He had come to the kingdom to seek the help of the dragons in a great battle against a powerful enemy. The golden dragon was intrigued and decided to help the king. ", 
    "The golden dragon realized it ought to offer assistance. It swooped down and carefully removed the branch from its jaws. The other dragon was thankful and expressed gratitude to the golden dragon for its aid. They conversed for a bit, and the golden dragon became aware that the other dragon was a monarch from a faraway realm. He had arrived in the kingdom to seek the aid of the dragons in a major conflict against a formidable foe. The golden dragon was captivated and made a decision to assist the king. ", 
    "The golden dragon was aware that it had to lend a hand. It descended to the dragon and delicately tugged the branch from its mouth. The other dragon was appreciative and thanked the golden dragon for its assistance. They conversed for a while, and the golden dragon discovered that the other dragon was a ruler from a distant land. He had come to the kingdom to request the support of the dragons in a great struggle against a powerful adversary. The golden dragon was fascinated and resolved to assist the king. " ],
  "sentence22": ["Together, the two dragons flew to the kingdom's castle to meet with the wise and just king. They told him of the impending danger and asked for his help. The king knew that he had to act quickly. He gathered his bravest knights and led them into battle against the enemy. ", 
    "In unison, the two dragons soared to the monarch's fortress to converse with the sagacious and equitable sovereign. They apprised him of the looming peril and requested his support. The sovereign apprehended that he must respond rapidly. He congregated his most courageous warriors and directed them into combat against the adversary. ", 
    "Simultaneously, the two dragons ascended to the kingdom's stronghold to confer with the wise and fair ruler. They informed him of the impending peril and requested his assistance. The ruler realized that he had to take action swiftly. He assembled his bravest knights and guided them into battle against the foe. " ],
  "sentence23": ["The battle was fierce, and many lives were lost. But in the end, the kingdom emerged victorious. The dragons had fought bravely alongside the knights, breathing fire and causing havoc among the enemy lines. The golden dragon had played a key role in the battle, using its cunning and experience to outmaneuver the enemy's dragons. ", 
    "The fight was intense, resulting in numerous casualties. Yet, in the end, the kingdom was triumphant. The dragons had fought courageously with the knights, spewing flames and causing damage to the hostile ranks. The golden dragon had been a decisive factor in the battle, utilising its strategy and know-how to outsmart the adversary's dragons. ", 
    "The combat was fierce, with a heavy toll of lives. Yet, in the conclusion, the kingdom was successful. The dragons had battled valiantly together with the knights, emitting fire and creating chaos amongst the enemy lines. The golden dragon had occupied a critical role in the conflict, employing its wisdom and expertise to outwit the enemy's dragons. " ],
  "sentence24": ["With the enemy defeated, the kingdom was safe once again. The golden dragon felt a sense of pride and joy, knowing that it had helped protect the kingdom and its people. ", 
    "The enemy's defeat meant the kingdom had been secured once more. The golden dragon felt a swell of satisfaction, with the knowledge that it had safeguarded the kingdom and its occupants. ", 
    "The foe was vanquished, making the kingdom secure again. The golden dragon was ecstatic, realizing that it had contributed to the guardianship of the kingdom and its citizens. " ],
  "sentence25": ["As the golden dragon and the other dragon king prepared to leave the kingdom and return home, they were approached by a small group of animals. Among them was a wise old frog, who had helped the magical potato many years before. ", 
    "The golden dragon and the other dragon king were getting ready to depart from the realm and go back to their residence when they were encountered by a handful of creatures. Among them was a sagacious elderly frog, who had aided the supernatural potato some years ago. ", 
    "As the golden dragon and the other dragon king were about to go away from the kingdom and come back to their abode, they were confronted by a small group of animals. One of them was an astute old frog, who was of assistance to the magical potato several years previous. " ],
  "sentence26": ["The frog approached the golden dragon and said, 'I have been watching you for many years, and I have seen how you have protected and cared for the kingdom's dragons. You have shown great courage and wisdom, and you have inspired many with your deeds. But now, it is time for you to rest.' ", 
    "The frog drew near to the golden dragon and uttered, 'I have been observing you for a long time, and I have noted your care and protection of the kingdom's dragons. You have been brave and sagacious, and you have stirred many with your actions. Nevertheless, now it is time for you to take a break.' ", 
    "The frog advanced to the golden dragon and declared, 'I have been keeping an eye on you for many years, and I have noticed your shelter and concern for the kingdom's dragons. You have displayed great valour and intelligence, and you have stirred many with your accomplishments. Yet, now it is time for you to relax.' " ],
  "sentence27": ["The golden dragon nodded, knowing that the frog was right. It had lived a long and happy life, and it was time for it to pass on its legacy to the next generation. The frog then turned to the other dragon and said, 'And you, young king, have shown great bravery and determination. You have proven yourself to be a worthy ally of the kingdom. I believe that you will one day become a great leader.'' ", 
    "The golden dragon nodded in agreement, realizing that the frog was correct. It had experienced a lengthy and joyous life, and it was time to pass down its inheritance to the subsequent generation. The frog then addressed the other dragon and proclaimed, 'And you, young king, have demonstrated immense courage and resolution. You have demonstrated yourself to be a faithful companion of the kingdom. I am certain that you will become an excellent ruler in the future.'' ", 
    "The golden dragon gave a nod, cognizant that the frog was accurate. It had lived an extensive and contented life, and it was time to hand over its heritage to the future generation. The frog then spoke to the other dragon and declared, 'And you, young king, have revealed tremendous courage and persistence. You have established yourself to be a reliable ally of the kingdom. I am confident that you will eventually become a great leader.'' " ],
  "sentence28": ["The other dragon thanked the frog and the golden dragon and took to the sky, ready to return to his own kingdom. The golden dragon watched as the other dragon flew away, feeling a sense of pride and hope. It knew that the kingdom was in good hands and that the legacy of the dragons would live on for generations to come. ", 
    "The other dragon expressed gratitude to the frog and the golden dragon before ascending into the heavens, prepared to go back to its own realm. The golden dragon observed as the other dragon flew away, feeling a sense of accomplishment and optimism. It was certain that the kingdom was in good hands and that the dragons' lineage would last for many years. ", 
    "The other dragon gave thanks to the frog and the golden dragon, then took off and headed for its own kingdom. The golden dragon gazed as the other dragon flew away, feeling proud and hopeful. It was sure that the kingdom was in safe hands and that the dragons' traditions would carry on for many generations. " ],
  "sentence29": ["As the golden dragon prepared to take its final flight, it looked out over the kingdom one last time. It saw the rolling hills, the majestic castles, and the bustling cities. And it knew that it had played a small part in making this kingdom great. With a final breath, the golden dragon took to the sky, its wings glimmering in the sunlight. As it flew higher and higher, it felt its body becoming lighter and more free. The pain in its chest was gone, and it knew that it was finally at peace. ", 
    "As the golden dragon readied for its concluding voyage, it surveyed the realm for the last time. It noticed the undulating hills, the grand fortresses, and the bustling towns. And it was aware that it had contributed a minor piece in rendering this kingdom splendid. With a concluding gasp, the golden dragon took to the heavens, its wings radiating in the daylight. As it lifted even further, it discerned its body becoming more feathery and liberated. The ache in its chest was gone, and it understood that it had finally attained contentment. ", 
    "As the golden dragon braced itself for its ultimate flight, it gazed out over the kingdom one last time. It observed the rolling hills, the magnificent castles, and the bustling cities. And it was aware that it had played a minor role in making this kingdom great. With a final breath, the golden dragon ascended to the sky, its wings gleaming in the sunlight. As it flew higher and higher, it felt its body becoming more buoyant and liberated. The distress in its chest was gone, and it knew that it had at last achieved harmony. " ],
  "sentence30": ["As it soared over the forest, the golden dragon saw a group of young dragons gathered in a clearing below. They were listening intently as an older dragon shared stories of battles won and enemies defeated. The golden dragon knew that its legacy would live on through these young dragons, who would continue to protect and care for the kingdom's people and dragons. ", 
    "On its flight through the forest, the golden dragon caught sight of a number of juvenile dragons assembled in an open area down below. They were completely engrossed in the tales of triumph that an elder dragon was narrating. The golden dragon was aware that its accomplishments would be remembered by these young dragons, who would keep on safeguarding and tending to the people and dragons of the kingdom. ", 
    "As it flew over the forest, the golden dragon observed a congregation of youthful dragons collected in a meadow beneath. They were intently paying attention as an older dragon recounted stories of victorious battles and conquered foes. The golden dragon knew that its heritage would live on through these juvenile dragons, who would persevere in protecting and caring for the kingdom's citizens and dragons. " ],
  "sentence31": ["With a final roar of triumph, the golden dragon flew higher into the sky until it was no longer visible to the naked eye. But its spirit remained, carried on the winds and echoed in the hearts of all who had been touched by its courage and wisdom. And so, the golden dragon's legacy lived on, inspiring generations to come. ", 
    "With a loud and victorious yell, the golden dragon ascended higher into the heavens until it became invisible to the human eye. But its impact persisted, travelling with the wind and instilled in the souls of those who had been touched by its bravery and knowledge. Consequently, the golden dragon's heritage continued, encouraging future generations. ", 
    "With one last triumphant roar, the golden dragon flew up into the sky until it could no longer be seen by the unaided eye. But the memory of it stayed, carried along the breeze and reverberating in the hearts of those it had inspired with its fortitude and sagacity. And thus, the golden dragon's legacy endured, motivating those to come. " ],



}

